### ISSUE TITLE
Adjust design of Energy system location page

### ISSUE THREAD

**Issue by deborabah** [centre-for-educational-technology/Seeds_bootstrap#4]
- can selection be made by interacting with the map?
- can the region be highlighted upon selection?

NB. Short descriptions of each region (About the Region section)  will be provided by the FC.ID team soon. 

<img width="1444" alt="Screenshot 2023-06-02 at 14 02 20" src="https://github.com/centre-for-educational-technology/Seeds_bootstrap/assets/82568880/d0195315-efbe-4fa6-a008-ec8332c02c47">

**Comment by pankajchejara23** [comment]
The feature is discarded later from the prototype.
